### PR TITLE
Move outline to glsl

### PR DESCRIPTION
**Pull request by thejohnhoffer**
I've moved the outline rendering from the canvas to WebGL with modifications to the fragment shader.

### CODE REVIEW

**Comment by thejohnhoffer** [comment]
It seems I've broken the rendering of the pie-chart centroids (OR-mode). 
I'll try to resolve that before marking as ready for review.

**Comment by thejohnhoffer** [comment]
> It seems I've broken the rendering of the pie-chart centroids (OR-mode). I'll try to resolve that before marking as ready for review.

Ah, it seems centroids are broken before my changes:
```
// Retrieve color (FIXME - need to integrate into viewer manager)
```

**Comment by thejohnhoffer** [comment]
I've filed the [OR-mode bug as a separate issue](https://github.com/labsyspharm/minerva_analysis/issues/93). I'll see if switching centroid mode to WebGL solves that problem.

**Comment by thejohnhoffer** [comment]
I've marked this PR as ready for review... I can handle the centroid rendering in another PR.

**Comment by kruegert** [comment]
renders very fast.


currently draws whole cells:
image
Could it draw outlines? This would be important to see the underlying image data.

Getting error:
gl not defined when changing color and color mapping slider on the left channel panel:
image
adding a this solves it:
const size_2fv = [this.gl.canvas.height, this.gl.canvas.width];

**Comment by tvquizphd** [comment]
ezgif com-gif-maker (25)

**Comment by tvquizphd** [comment]
I've moved more of the logic to the shaders... there's one more rendering optimization I'd like to make before reviewing for the merge.

**Comment by thejohnhoffer** [comment]
I've moved more of the logic to the shaders... there's one more rendering optimization I'd like to make before reviewing for the merge.

**Comment by thejohnhoffer** [comment]
I've solved the pie chart issue for 4+ markers... there is still an optimization on the ordering of selection kesy.

**Comment by thejohnhoffer** [comment]
showing outlines and or mode)

**Review by thejohnhoffer — COMMENTED** [review]
I've updated the image viewer so that it doesn't render images when the gating parameters are loading from the server. One last step may be to add a loading icon so the users know when the client is waiting on the server.

**Pull request merged**
